### ISSUE TITLE
Easy prototyping on GOV.UK PaaS

### ISSUE THREAD

**Issue by markpeterbuckley** [alphagov/paas-roadmap#100]
**Is your feature request related to a problem? Please describe.**
Developers often create rapid prototypes for user testing purposes or to try out different designs. Being able to easily deploy prototypes to GOV.UK PaaS in the same manner that they do to Heroku would be beneficial.

**Is this blocking you from doing anything?**
It means developers lean more towards the easy prototyping functionality on Heroku

**Describe the outcome you'd like**
* Being able to host GOV.UK UK prototypes in a similar way to pushing to Heroku as per https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku
* It should work with basic app patterns like rails + db with no or minimal configuration

**Describe the solutions you've considered**
Use Heroku instead

**Additional context**
The GOV.UK prototyping kit already has instructions for pushing apps to Heroku but not GOV.UK PaaS

**Support links (for GOV.UK PaaS folk only)**
https://govuk-prototype-kit.herokuapp.com/docs/publishing-on-heroku

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
