### ISSUE TITLE
[Feature Request] - Export metrics for instance counts

### ISSUE THREAD

**Issue by vlaurin** [alphagov/paas-roadmap#101]
**Is your feature request related to a problem? Please describe.**
N/A

**Is this blocking you from doing anything?**
The absence of exported metrics relating to the count of instances prevents from:
- Building visualisations and dashboards tracking application availability (counts of total instances, healthy instances, unhealthy instances)
- Configure alerts on count of unhealthy instances
- Visualise auto-scaling events

**Describe the outcome you'd like**
The metrics exporters (prometheus and statsd) should export for each CF app the total count of instances and the count of instances in each state, as reflected by the `cf app <name>` view.

For example, the prometheus exporter could expose a record with the following fields:
```
prometheus.labels.app = 'app-name'
... other labels
prometheus.metrics.instance_total_count = 3
prometheus.metrics.instance_running_count = 2
prometheus.metrics.instance_crashed_count = 1
prometheus.metrics.instance_starting_count = 0
... counts for other instance states?
```

**Describe the solutions you've considered**
Excluding `cf app <name>`, there doesn't seem to be a way to directly monitor instance health.

The metric `prometheus.metrics.crash` can be used as an indicator of an instance being unhealthy but it cannot be used to derive overall application availability (eg. 1 instance down but 2 instances still up). The `crash` metric is also incremented for failed blue/green deployments which didn't affect availability.

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
