### ISSUE TITLE
[Feature Request] - Autoidle / Scaling down to 0 

### ISSUE THREAD

**Issue by matthewford** [alphagov/paas-roadmap#102]
**Is your feature request related to a problem? Please describe.**
Looking at cost reduction, we have some environments that are not actively used, for example, dev/staging, it would great if we could automatically scale these to 0 and then boot them up when they receive traffic, similar to https://elements.heroku.com/addons/autoidle

This might be possible with the existing autoscaler, but most examples use 1 as a minimum.

**Comment by markpeterbuckley** [comment]
Hi Matt, sorry for not coming back to this sooner. 

"This might be possible with the existing autoscaler, but most examples use 1 as a minimum."

Unfortunately this is a technical constraint and so without so rather ugly workarounds we won't be able to do it at the moment. Potentially something for upstream to think about. Are there other ways to achieve what you need? CI/CD maybe?
