### ISSUE TITLE
[Feature Request] - Allow vanity URLs for S3 assets

### ISSUE THREAD

**Issue by simon4342** [alphagov/paas-roadmap#103]
**Is your feature request related to a problem? Please describe.**
We have a Drupal site, hosted on the gov.uk PaaS platform. We store images and files on S3. The public-facing URLs for those assets show the full S3 path, meaning that when a user downloads a PDF for example, they sometimes see the URL and wonder if they can trust the link as it doesn't seem to be coming from our site. We have also had contact from a security person at a police force to say that their users are often blocked when trying to download from our site, because the local policy sees S3 as a file sharing site.

**Is this blocking you from doing anything?**
Not really, but it doesn't look nice, and it's causing confusion and wariness from users. Users at some police forces are being blocked by IT policy.

**Describe the outcome you'd like**
We would like the public-facing URLs to use our own domain/subdomain.

**Describe the solutions you've considered**
We did consider setting up a proxy or deploying another app to point at instead, but there wasn't much enthusiasm for those methods. We would ideally like the gov.uk platform to be able to handle this functionality without the need for workarounds.

**Support links (for GOV.UK PaaS folk only)**
4144065

Thanks

**Comment by markpeterbuckley** [comment]
Hi Simon. Thanks for making the request. We will add this to the backlog and prioritise accordingly. There are a number of 'S3 enhancements' we'd like to do but depends on priority of other things of course.

**Comment by simon4342** [comment]
Thanks Mark. We'll watch this space.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
