### ISSUE TITLE
[Feature Request] - Restrict S3 service access by IP address

### ISSUE THREAD

**Issue by baarkerlounger** [alphagov/paas-roadmap#107]
**Is your feature request related to a problem? Please describe.**
Using S3 as a file transfer mechanism to external services is less secure than it could be as access can't be restricted by VPC endpoint/IP address

**Describe the outcome you'd like**
A way to set access policies on Gov PaaS S3 service buckets that restrict access by VPC endpoint or IP addresses

**Additional context**
AWS supports this via bucket policies (https://aws.amazon.com/premiumsupport/knowledge-center/block-s3-traffic-vpc-ip/)

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by wryobservations** [comment]
Hello - thanks for this request and the others you've submitted recently. We've long been hoping to play a small mission around enhancing the S3 feature set. I've added this to that group of stories. Right now we're mostly concentrating on core platform operations work.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
