### ISSUE TITLE
[Feature Request] - Sentry backing service

### ISSUE THREAD

**Issue by baarkerlounger** [alphagov/paas-roadmap#108]
**Is your feature request related to a problem? Please describe.**
Many applications being run on Gov PaaS require an application error monitoring and alerting solution. [Sentry](sentry.io) is a popular open source choice that works for the vast majority of languages/frameworks in use. There is also an AWS Marketplace version of it (https://aws.amazon.com/marketplace/pp/prodview-h4yamnwqqyki2). 

**Is this blocking you from doing anything?**
No but it adds friction to set up

**Describe the outcome you'd like**
A managed, hosted Sentry backing service provided by Gov PaaS that can be set up and billed in the same way as other backing services.

**Describe the solutions you've considered**
Using the Sentry.io managed, hosted service.

**Additional context**
The Sentry.io managed service hosts data in the US and requires a stored credit card for small plans which adds friction to set up for Gov services.

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
