### ISSUE TITLE
[Feature Request] - Prometheus/Grafana backing service

### ISSUE THREAD

**Issue by baarkerlounger** [alphagov/paas-roadmap#109]
**Is your feature request related to a problem? Please describe.**
Many applications being run on Gov PaaS require a monitoring and alerting solution for infrastructure and application metrics. [Grafana](https://grafana.com/) and [Prometheus](https://prometheus.io/docs/introduction/overview/) are a popular open source choice suitable for most applications.

**Is this blocking you from doing anything?**
No both are open source so can be run on Gov PaaS ourselves but it would be a lot quicker and simpler to have it provided as a Gov PaaS backing service.

**Describe the outcome you'd like**
Gov PaaS backing service for Prometheus/Grafana that can be created and billed similar to other backing services. It would be able to export and monitor metrics from all applications running in your account.

**Describe the solutions you've considered**
Running instances of Prometheus/Grafana on Gov PaaS ourselves in a dedicated monitoring space.

**Additional context**
This would simplify and help standardise productionisation of many applications.

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
