### ISSUE TITLE
Improve support for data science workloads

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#15]
## Objective

Make it easier for people to run data science workloads on GOV.UK PaaS

## What we think we know

Data science workloads are good workloads to support

## What we don’t know

* Where people are having trouble presently
* What, if any, additional backing services people need (Queues, Time series database)

## How we’ll find out more

* User research
* Spikes

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
