### ISSUE TITLE
AWS SQS Queues

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#16]
**Is your feature request related to a problem? Please describe.**
I am unable to deploy applications that require a queue natively on PaaS

**Is this blocking you from doing anything?**
Yes from deploying applications that expect a message queue to use as a backing service

**Describe the outcome you'd like**
The ability to create queue services from a broker

**Describe the solutions you've considered**
Workarounds can be created using celery in python, but this requires additional development time and expense

**Additional context**
**Key results**

* Validated assumptions around user needs
* Queuing system is offered as a backing service
* Tenants are using it

**What we don’t know**

* SQS or something else (e.g. RabbitMQ or some other AMQP based system)

**Comment by pauldougan** [comment]
@gidsg Thanks for the feedback about queues at the tech community event today. If you could share some thoughts on the topic here about how it could have helped https://github.com/heritagefund that would be great and what your needs are that would be great. That way we can feed it into our planning.

**Comment by gidsg** [comment]
> how it could have helped https://github.com/heritagefund 

There are 2 potential use cases I can see:
* For processing queues within the app. For example using something like https://github.com/phstc/shoryuken
* For improving resilience of 3rd party integrations by having them push & pull messages from a queue rather than making HTTP requests directly to the app.

CC @stuartmccoll

**Comment by pauldougan** [comment]
The document checking service currently uses [AWS SQS](https://aws.amazon.com/sqs/) in its audit logging system. Native support for SQS would assist the replatforming

The Automate public roadmap has a story in scope for this quarter [Prepare to migrate the Document Checking Service to PaaS #11](https://github.com/alphagov/automate-roadmap/issues/11)

**Comment by pauldougan** [comment]
more context around the use of SQS in the DCS => https://github.com/alphagov/doc-checking/blob/govuk-paas/doc/paas-discovery/009-audit-queue.md

**Comment by pauldougan** [comment]
https://github.com/alphagov/automate-roadmap/issues/21

**Comment by pauldougan** [comment]
@markpeterbuckley given you make the announcement of the availability of this service ont he announcement group, I think we can move this over into the done column

**Comment by markpeterbuckley** [comment]
Ah yes, I'll update the information in the card to point to the docs, too 👍

**Comment by markpeterbuckley** [comment]
What have we done?
------------------

We now offer Amazon Simple Queue Service (SQS) through [GOV.UK](http://gov.uk/) PaaS. SQS offers a durable hosted queue that lets you build decoupled distributed software components.

There are two types of plan available for the service:

-   `standard`, providing at-least-once delivery, where each message is delivered at least once
-   `fifo`, for first-in-first-out queues providing [exactly-once processing](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-exactly-once-processing), where each message is delivered once and remains available until a consumer processes it and deletes it

AWS SQS queues can be configured to move messages that cannot be successfully processed by your application on a secondary queue, known as a [dead-letter queue](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html), letting you isolate problematic messages to determine why their processing did not succeed.

How do I use it?
----------------

You can learn how to [set up queues with your service by reading our documentation](https://docs.cloud.service.gov.uk/deploying_services/sqs/#amazon-sqs)

This is a beta service which is currently in a testing phase. If you would like to test the service, you will need to contact the [GOV.UK](http://gov.uk/) PaaS team at [gov-uk-pa...@digital.cabinet-office.gov.uk](https://groups.google.com/).

How do I give you feedback?
---------------------------

-   Comment on the public roadmap issue for this feature here: <https://github.com/alphagov/paas-roadmap/issues/16>
-   Email us at [gov-uk-pa...@digital.cabinet-office.gov.uk](https://groups.google.com/). if you have any private feedback, or need any help.
-   You can also talk to us via the cross-government Slack channel #govuk-paas on the UK Government Digital workspace, or the GDS Slack channel #paas

Thanks,\
The [GOV.UK](http://gov.uk/) PaaS Team
