### ISSUE TITLE
Improve user experience for custom domains

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#18]
## Objective

Make it easier for GOV.UK PaaS users to get a custom domain for their service

## Key results

Custom domains can be obtained in a more reliable way

## Stretch goal

Wildcard domains

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
