### ISSUE TITLE
Make Continuous integration / Continuous delivery (CI/CD) easier

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#20]
## Objective

Make it easier for GOV.UK PaaS users to set up continuous integration and continuous deployment, in a secure way.

## Linked issues

"Make it easier for users to preview changes to their apps": https://github.com/alphagov/paas-roadmap/issues/54

"Ephemeral services that start quickly (for PR reviews etc.)" https://github.com/alphagov/paas-roadmap/issues/59

**References**
- ZENDESK-3996575

**Comment by pauldougan** [comment]
also see zendesk [3996575]()https://govuk.zendesk.com/agent/tickets/3996575

**Comment by saliceti** [comment]
I am already implementing https://github.com/alphagov/paas-roadmap/issues/54 which is trivial to do using paas and the [cf terraform provider](https://github.com/cloudfoundry-community/terraform-provider-cf)
But it takes too long to build and destroy services. Which is where https://github.com/alphagov/paas-roadmap/issues/59 would really really help.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
