### ISSUE TITLE
Encourage users to restage their applications often

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#21]
# Objective

In order to reap the benefits of GOV.UK PaaS buildpacks, applications should be restaged often

## Research Considerations

We need to undertake a bit of user research on this before we know how it should work. Some of the considerations are;
* What happens if my restage fails?
* Should it be in a blue / green state to avoid any service interruption?
* Should notifications of failures / successes be sent?
* What happens with applications where there is no live team to action requests?
* Should restages be schedulable by tenants?
* Should restages be sequenceable?
* Should restages be opt in or opt out?

## Key results

* We know how often people restage their apps
* We ensure that applications are restaged often

**Comment by matthewford** [comment]
Could allow an option for a nightly restage, similar to Heroku (granted that's a restart not a restage).

**Comment by LeePorte** [comment]
Hi @matthewford I've added in some user research considerations into the issue, as I think this is one that we'll need to do some fairly detailed research on in order to not have unintended consequences. Are there any other issues to research that you can think of?

**Comment by tlwr** [comment]
It could be interesting to use `labels` for this eg `cf set-label app my-app paas-restage-nightly=true`

**Comment by richardTowers** [comment]
It's worth mentioning that it's only really necessary (from a security perspective) to restage apps when they use a platform buildpack and we've released a new version. Stack updates (with OS level security patches) get rolled out without the need for a restage.

I don't know what the best UX would be for that - for some apps an automatic restage as soon as the new buildpack is released might be appropriate (but obviously it would need to be `--strategy rolling` or whatever), for some it might be better to just notify the org that they need to restage / redeploy.

To fold Toby's suggestion into that thought, maybe something like:

```
cf set-label app my-app on-buildpack-update '{"action": "notify-org-owners"}'

cf set-label app my-app on-buildpack-update '{"action": "restage", "time": "immediately"}'

cf set-label app my-app on-buildpack-update '{"action": "restage", "time": "01:00:00.000Z"}'
```

**Comment by matthewford** [comment]
> unintended consequences

Well in 2018, The buildpacks were updated removing a ruby version which we used (as we pinned to the patch level). 

Now, buildpack updates are broadcast to tenants prior to the upgrade 😄 

We also target pessimistic versions of Ruby, not down to the patch level, which is something people would need to do prior to using something like an auto-restage, although, given the buildpacks can update at any point, they should do that anyway.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
