### ISSUE TITLE
Provide better Denial of Service protection for GOV.UK PaaS users

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#22]
## Objective

As a GOV.UK PaaS user, I want to ensure that mitigations are in place to minimise the impact of a DDoS attack

## Key results

GOV.UK PaaS tenants have access to DDoS protection

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
