### ISSUE TITLE
Elasticsearch backing service metrics via Prometheus endpoints

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#25]
## Objective

Enable our users to manage their Elasticsearch backing services more confidently, so they can:

- Avoid unnecessary reliability problems for users through capacity issues

- Reduce unnecessary costs through sizing their backing services more accurately

## How we'll solve the problem

We already provide these metrics via the GOV.UK PaaS admin interface. 

In addition, we will:

- Enable users to set up dashboards and alerts, via Prometheus endpoints

## Key Results:

- We are emailed less often by Aiven about Elasticsearch clusters "running low on resources"
- 80% of eligible users have set up alerts on their Elasticsearch disk space

## Dependencies: 

- Setting up a process for feedback loop

**Comment by 46bit** [comment]
This is now ready for tenants to use! 🎉 I've split out Redis metrics into https://github.com/alphagov/paas-roadmap/issues/74, and that's also just about ready.

**Comment by 46bit** [comment]
How to adopt this is now documented at https://docs.cloud.service.gov.uk/monitoring_services.html#exporting-backing-service-metrics-to-prometheus.
