### ISSUE TITLE
Apache Kafka

### ISSUE THREAD

**Issue by emilyhectorlabram** [alphagov/paas-roadmap#34]
**Is your feature request related to a problem? Please describe.**
I am unable to use stream processing within applications deployed on GOV.UK PaaS. The use case is for gathering CVE and emerging threat data from the web and deduplicating this before presenting the cleansed data as actionable insights for our user base.

**Is this blocking you from doing anything?**
Currently we are unable to use GOV.UK PaaS for this application

**Describe the outcome you'd like**
Apache Kafka to be available via `cf marketplace`

**Describe the solutions you've considered**
Hosting elsewhere

**Additional context**
With the addition of Apache Kafka it would be possible to host on GOV.UK PaaS and this would reduce our hosting costs.

**References**
- ZENDESK-3917819

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
