### ISSUE TITLE
Users can run PCI-compliant services

### ISSUE THREAD

**Issue by emilyhectorlabram** [alphagov/paas-roadmap#36]
## Objective

Enable our users to run services on GOV.UK PaaS which can be certified as PCI compliant.

## What problem does this solve?

We are onboarding a new user, GOV.UK Pay. This service handles sensitive card-holder data.

The improvements we make in order to achieve this may have benefit to other users who need to achieve higher levels of security.

## Key Results

- Our users can meet 100% of PCI regulations when hosting their service on GOV.UK PaaS

##  Dependencies

- Capacity of Pay team and Cyber team 

##  Risks 

- Not being compliant blocks migration of platform
- Increased complexity to PaaS resulting increase workload in support.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
