### ISSUE TITLE
Create 'production ready apps' documentation

### ISSUE THREAD

**Issue by emilyhectorlabram** [alphagov/paas-roadmap#38]
## Objective

Help users set and meet their own reliability goals, or "Service Level Objectives" for their services hosted on GOV.UK PaaS by giving best practice guidance for running live applications.

## What problem are we solving?

Research into our users' support tickets tells us that:

New users of the GOV.UK PaaS are sometimes unaware of what they need to do to achieve high levels of reliability for their services. 

Examples include:

- Using blue-green deployments to reduce downtime

- Choosing to run several instances of their applications

When they make changes to their services, they can **unknowingly cause reliability problems for users**.

### Another problem to solve:

Also, our support engineers often do not know what level of reliability our users are expecting or needing for their services. 

This means that:

- Investigations involve more back-and-forth in order to understand the reliability levels needed

- Support engineers may either invest too much time, or too little time, trying to solve a problem for users

## Our hypothesis for solving these problems

We think that if we make it easier for users to:

- share their reliability goals with us

- understand what they need to do to achieve them

Then we will see these results:

## Key Results

- Users' confidence in their ability to meet Service Level Objectives significantly improves

- Engineers supporting GOV.UK PaaS feel significantly more confident in their ability to prioritise problems on behalf of users

- New services hosted on GOV.UK PaaS achieve higher levels of reliability for end users

## References
- 'Encourage users to restage their applications often' https://github.com/alphagov/paas-roadmap/issues/21
- ZENDESK-4381993

**Comment by markpeterbuckley** [comment]
https://github.com/alphagov/paas-roadmap/issues/21
