### ISSUE TITLE
Support dynamic billing 

### ISSUE THREAD

**Issue by emilyhectorlabram** [alphagov/paas-roadmap#40]
**Is your feature request related to a problem? Please describe.**
At present GOV.UK PaaS billing is unable to cope with usage based priced AWS services such as SQS and heavy S3 usage

**Is this blocking you from doing anything?**
It blocks us from offering demand based priced services to tenants 

**Describe the outcome you'd like**
The ability for the billing application to be able to cope with priced according to usage services

**Describe the solutions you've considered**
Flat fee approaches, but these are brittle and don't reflect real usage

**Additional context**

**References**
- ZENDESK-4209612

**Comment by pauldougan** [comment]
ZENDESK-4209612

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
