### ISSUE TITLE
Provide a what's new and change log

### ISSUE THREAD

**Issue by markpeterbuckley** [alphagov/paas-roadmap#43]
## What

As a user of PaaS
I want to know if the platform has changed
So that I can understand more about my service

As a user of PaaS
I need to know if anything on the platform has changed recently
In order to give more observability 

As a user of PaaS
I want to know what features have recently been released
So that I can improve my service

As prospective user of PaaS without an account
I want to see how the platform has developed over time
So that I can understand its direction of travel and evaluate possible uses of the platform

## Why
* A number of support requests are enquiries asking about whether the platform has changed
* Interested parties don't always know about newly released features that may benefit them or help with evaluation

### Key results
* fewer support enquiries about changes 
* increased awareness of what the platform provides

### Dependencies
None

### Risks
Keeping up to date

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
