### ISSUE TITLE
Make it easier for users to preview changes to their services

### ISSUE THREAD

**Issue by emilyhectorlabram** [alphagov/paas-roadmap#54]
## Objective

Enable users of GOV.UK PaaS to more easily "review" changes they want to make to their services, e.g.

> As a Product Manager, 
When my team has finished working on a story
I want to review it
So that I can check that it will meet users' needs before we release the change

## Key results

- Significant reduction in time between a story being "in review" and deployed to production

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
