### ISSUE TITLE
Microsoft SQL Server

### ISSUE THREAD

**Issue by pauldougan** [alphagov/paas-roadmap#55]
**Is your feature request related to a problem? Please describe.**
As a GOV.UK PaaS user I want to be able to provision Microsoft SQL Server from `cf marketplace` so I that I can use it as a data store for relational data, so that my .NET core applications hosted on GOV.UK PaaS are able to access the data.

**Is this blocking you from doing anything?**
I am unable to use the tools that I am familiar with when building .NET application on GOV.UK PaaS

**Describe the outcome you'd like**
As a GOV.UK PaaS user I want to be able to provision Microsoft SQL Server from `cf marketplace` so that I can use it for relational database workloads.

**Describe the solutions you've considered**
Having to learn another set of tools to use an alternative RMDBS.

**Additional context**
Subject to a spike: https://www.pivotaltracker.com/n/projects/1275640/stories/170722390

**References**
- ZENDESK-2853903
- ZENDESK-4193441

**Comment by pauldougan** [comment]
see ZENDESK-2853903

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
