### ISSUE TITLE
Memcached

### ISSUE THREAD

**Issue by pauldougan** [alphagov/paas-roadmap#56]
**Is your feature request related to a problem? Please describe.**
As a GOV.UK PaaS user I want to be able to provision [Memcached](https://memcached.org/) from `cf marketplace` so I that I can use it for caching data store so that my service can migrate to the platform.

**Is this blocking you from doing anything?**
I am currently unable to migrate applications that use [Memcached](https://memcached.org/)

**Describe the outcome you'd like**
As a GOV.UK PaaS user I want to be able to provision [Memcached](https://memcached.org/)  from `cf marketplace` so that I can use it for caching.

**Describe the solutions you've considered**
Rewriting part of the application to use Redis as a cache

**Additional context**

**Comment by matthewford** [comment]
We currently use redis with different namespaces but there is a chance that the db fills up and that then impacts other services we run off redis (background queues)

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
