### ISSUE TITLE
Support cache invalidation in CDNs

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#58]
At least one use is currently using their own CDN because GOV.UK PaaS's broker-provided CDNs don't allow users to invalidate their cache.

Cloud Front has support for invalidating cached files:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

We could surface this to users through the broker somehow.

**Comment by matthewford** [comment]
We have aggressive caching in the Trade Tariff and we occasionally have to clear the entire cache, a cli command or a web ui would be sufficient.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
