### ISSUE TITLE
More configurable CDN service

### ISSUE THREAD

**Issue by richardTowers** [alphagov/paas-roadmap#60]
For the recent GOV.UK coronavirus services, we used a custom Amazon CloudFront CDN instead of using the GOV.UK PaaS one.

We ended up using a few features of the CDN which aren't available in the PaaS provided CDNs. Some of these feel like they would be generally very useful.

## Custom cache behaviour for assets

[Our terraform](https://github.com/alphagov/tech-ops-private/blob/3ecd66e12a7fa823113dc0bc775185f28b488049/reliability-engineering/terraform/deployments/corona-data-staging/account/cloudfront_vulnerable_people.tf#L42-L55) uses a custom cache behaviour for assets. If we don't do this we get extremely poor cache hit rates, because we have to forward cookies to the origin (because we need sessions). Having a custom cache behaviour allows us to get decent caching for assets.

<details><summary>Terraform snippet for those without access to the private repo in the link above</summary>

```terraform
  ordered_cache_behavior {
    path_pattern     = "/assets/*"
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "govuk-coronavirus-vulnerable-people-staging"

    forwarded_values {
      query_string = false
      headers      = ["Host", "Authorization"]

      cookies {
        forward = "none"
      }
    }
```

</details>

## Allow using paas-provided S3 buckets as a custom origin for assets

Lots of frameworks (e.g. Rails) generate assets with hashes of the contents in the filename. This makes doing rolling deployments tricky without serving some 404s for assets. A solution to this is to upload the assets to S3 and serve them from there. We're planning on using a custom origin to serve the assets from the same CDN domain - https://github.com/alphagov/tech-ops-private/pull/252/files. Using the CDN for assets is nicer than serving them from S3 because you get edge caching and fewer TCP connections need to be made.

It would be nice if we could have used a paas S3 bucket for this.

**Comment by tlwr** [comment]
Adding some omakase WAF (web application firewall) rules to the CDN distributions could be in scope for this feature, which would facilitate better IP safelisting.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
