### ISSUE TITLE
allow tenants to control the RDS database backup retention period 

### ISSUE THREAD

**Issue by pauldougan** [alphagov/paas-roadmap#62]
Some tenants require more control over the retention of RDS database snapshots. At the moment the PaaS has a set limit of 7 days defined for everyone. The underlying AWS platform can go as high as 35 days. 

Tenants may want to opt for reduced retention period for ephemeral copies of application in test environments or may way to have longer retention periods to comply with departmental data management policy. 

**References**
- ZENDESK-4180890
- ZENDESK-4090770
- ZENDESK-4204012
- ZENDESK-4895497
- ZENDESK-4896896

**Comment by AP-Hunt** [comment]
See ZENEDSK-4180890

**Comment by pauldougan** [comment]
See ZENDESK-4090770

**Comment by jamesgriff** [comment]
Hi,

I though I'd share why this feature would be useful for my team.

I'm technical lead of the [Gender Pay Gap service](https://gender-pay-gap.service.gov.uk) ([GitHub repo](https://github.com/cabinetoffice/gender-pay-gap))

For most of the year, our service is non-urgent and has low traffic (most users use it in March, just before an annual deadline).
Over holiday periods (e.g. Christmas) it's likely that no-one will be using the service for up to 2 weeks.
If a data corruption happened during this period, it's possible that we wouldn't notice for >7 days and so the data would be lost forever.

We'd appreciate being able to use the full 35 days of snapshots.

We're currently hosted on Microsoft Azure, but moving to Gov.UK PaaS in the next few weeks.
Our current plan is to make do with the 7 days of backups for the next few months, but we'll need a solution before Christmas. We're expecting to build a custom solution using conduit / pgdump, but it would be fantastic if we didn't need to spend the time building this solution.

Let us know if there's anything we can do to help.

All the best,
James

**Comment by markpeterbuckley** [comment]
Hi @jamesgriff thanks for your feedback. This is indeed something that has been raised by other tenants and something we are looking to implement within your timescales. We need to do some pre-work on our billing engine to be able to support this, however, then lots of things should be able to be enabled. Thanks, Mark.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
