### ISSUE TITLE
Billing API 

### ISSUE THREAD

**Issue by saliceti** [alphagov/paas-roadmap#63]
The billing dashboard is very good and allows to see monthly usage by org and spaces. It can be used by the finance team at the end of the month for cross charging product teams.

However, this is a slow feedback for the product teams and they may be consuming a lot of resources before realising it at the end of the month. It is possible to see the current month usage, but it's a manual process to login to the website and look at figures or download the spreadsheet.

If there were an API showing daily usage for spaces, I would be able to set up alerting, dashboards, forecasts for each team so they can control costs in a much more granular way.

**Comment by markpeterbuckley** [comment]
As discussed, I've folded this into https://github.com/alphagov/paas-roadmap/issues/97 so going to close this. Hope to give you some updates soon! 👍
