### ISSUE TITLE
Support versioned object storage

### ISSUE THREAD

**Issue by tlwr** [alphagov/paas-roadmap#64]
What
----

GOV.UK PaaS currently supports object storage with Amazon S3.

Amazon S3 allows objects to have versions, which are automatically assigned when objects are updated.

The GOV.UK PaaS S3 broker should support object storage

User stories
----

As a user, I can create a versioned s3 bucket with
```bash
$ cf create-service aws-s3-bucket versioned my-versioned-bucket
```

As a user, I can convert a bucket from unversioned to versioned with
```bash
$ cf update-service my-bucket -p versioned
```

As a user, I CANNOT convert a bucket from versioned to unversioned with
```bash
$ cf update-service my-versioned-bucket -p default
```

As a user, when I convert a bucket from unversioned to versioned, I must rebind my apps to give them the correct permissions with
```bash
$ cf unbind-app my-app my-bucket
$ cf bind-app my-app my-bucket
```

Who wants this
----

Anecdotally, a few; specifically @uktrade

**Comment by munhitsu** [comment]
👍

**Comment by 46bit** [comment]
DfE reported this block using AWS Terraform's `data "aws_s3_bucket_object"`, because it relies on making a `GetObjectTagging` API call https://github.com/hashicorp/terraform-provider-aws/blob/a6a0a96479fbcb328eb3fb3cf53764b62fb3ca16/aws/data_source_aws_s3_bucket_object.go#L228

**Comment by saliceti** [comment]
As mentioned in https://github.com/alphagov/paas-roadmap/issues/64#issuecomment-738929637 this would allow reading a file from terraform or other tools for dynamic configuration. For example storing a yaml file, accessing it via a terraform data source, decode yaml and create a map variable to configure terraform resources.

This could also open a lot of use cases as this automatically provides backup and the ability to revert to a previous version in case of corruption. For example:
- store terraform state
- secrets stored in a yaml or json file
- feature flags

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
