### ISSUE TITLE
Enable service sharing in brokers

### ISSUE THREAD

**Issue by tlwr** [alphagov/paas-roadmap#65]
What
----

As a user I would like to be able to run `cf share-service` to share my service with another space (which could be in another org), so that I can use service bindings across spaces.

An example use case
----

The [Department for Education](https://github.com/DFE-Digital) have a backup and restore process which uses [Conduit](https://plugins.cloudfoundry.org/#conduit) to sync data from their production environment to their staging environment.

```bash
# Share the service
cf target -s production
cf share-service my-production-db -s staging
```

```bash
# Push data sync app
cf target -s staging
cf push my-data-sync-app --no-route
cf bind-service my-data-sync-app my-staging-db
cf bind-service my-data-sync-app my-production-db
```

```ruby
# Sync some data from production to staging
databases = JSON.parse(ENV.fetch('VCAP_SERVICES')).dig('postgres')

staging_db = {
  adapter:  'postgres',
  url: databases.dig('my-staging-db', 'credentials', 'uri'),
}

production_db = {
  adapter:  'postgres',
  url: databases.dig('my-production-db', 'credentials', 'uri'),
}

scheduler.every '6h' do
  # Get some data from production
  ActiveRecord::Base.establish_connection(production_db)
  users = User.find_in_batches(50)

  # Save it to staging
  ActiveRecord::Base.establish_connection(staging_db)
  users.each(&:save)
end
```

In this example, an app running a scheduler performs a sync every 6 hours. All data is kept within the platform, and credentials are managed automatically using service bindings, instead of service access keys and user provided services.

**Comment by pauldougan** [comment]
This has now shipped and is available for tenants to use 

https://www.pivotaltracker.com/n/projects/1275640/stories/173220546
