### ISSUE TITLE
Add pg_audit_level to RDS service binding

### ISSUE THREAD

**Issue by tlwr** [alphagov/paas-roadmap#66]
**Overview**

> As a user of Postgres via the GOV.UK PaaS RDS Broker
I want to configure pgaudit in my database
So that I can audit what users do.

Currently, the RDS broker does not allow users to configure `pgaudit` as this requires more privileges.

When creating a Postgres service binding it should be possible to add `pg_audit_level` (eg `ALL` `WRITE` `READ`) as a service binding argument:

```
cf bind-service my-app my-db -c '{"pg_audit_level":"WRITE"}'
```

and `pgaudit` will be configured for the role used by the binding.

There should be no auditing configured by default as this changes the performance characteristics of the database

**Is this blocking you from doing anything?**

Support tickets have been raised on this issue

**Describe the outcome you'd like**

As a user,
when I create a service binding with `pg_audit_level` specified,
`pgaudit` is configured,
and I can see the audit information in the `Logs` tab in the GOV.UK PaaS admin interface

As a user,
when I create a service binding with `pg_audit_level` specified,
and `pgaudit` is not enabled as an extension,
I should get a friendly error message

**Describe the solutions you've considered**

`cf events` and GOV.UK PaaS admin interface show off events like connecting to the database but not granular events such as queries.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
