### ISSUE TITLE
Make it easier to estimate the cost of a service on GOV.UK PaaS

### ISSUE THREAD

**Issue by emilyhectorlabram** [alphagov/paas-roadmap#69]
### Is your feature request related to a problem? Please describe.

Users experience problems when to use the pricing calculator on the GOV.UK PaaS website to estimate running costs for their applications and backing services.

This is particularly challenging for users without any technical expertise, but it's still difficult for technical users.

### Describe the outcome you'd like

When a user is trying to estimate the running costs of their service, they can easily figure this out.

When a user wants to decide which size and type of backing service they want, they can easily compare costs.

### Describe the solutions you've considered

- Make it easier to find the calculator
- Make it easier to understand and compare the plans available
- Make these user journeys accessible

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
