### ISSUE TITLE
Make practising Infrastructure as Code easier

### ISSUE THREAD

**Issue by chrisfarms** [alphagov/paas-roadmap#70]
## Objective

Encourage the practice of describing deployments in a declarative, infrastructure as code manor as [recommended in the service manual](https://www.gov.uk/service-manual/technology/manage-your-software-configuration#use-infrastructure-as-code)

## Current state

* GOV.UK PaaS documentation is generally geared towards an imperative style of "type this into the cli once" - this makes repeating the process error prone or requires creating scripts that automate the typing of commands
* Cloudfoundry manifests offer a partial solution to this problem but there are large common sections of the API that are not covered by the manifests (network policies, service creation, deletion, etc)
* A [cloudfoundry terraform provider](https://github.com/cloudfoundry-community/terraform-provider-cf) exists, but it is a bit unloved, has poor documentation and GOV.UK PaaS users of it would need to work out where to store their state

## Improved state

I'd love to see:

* Both "imperative" and "declarative" options for each action throughout the documentation
* A recommended route to getting started with a more declarative style (terraform? a cf plugin? helper scripts? something else?)
 
## Context

**Is your feature request related to a problem? Please describe.**

While porting some applications to GOV.UK PaaS where we needed to continuously create and destroy environments we quickly moved from scripts to terraform ... however using custom terraform providers isn't fun† (each user needs to install plugin, sometimes in weird locations), the best docs were the code itself... whenever we had to refer to the paas docs, we needed to translate what "cf cli" commands were being explained into the declarative format .... none of this is "hard" but did feel like friction .... we also relied heavily on external ci/cd infrastructure (that other tenants likely would not have!) for storing our state

† update: the new [terraform registry](https://registry.terraform.io/) simplify provider management in v0.13+

**Is this blocking you from doing anything?**

Nope, just think we can do more to promote best practices

## Related

* https://github.com/alphagov/paas-roadmap/issues/20
* https://github.com/alphagov/paas-roadmap/issues/59

**Comment by rjbaker** [comment]
Thanks for opening this @chrisfarms. 

I can share some of GOV.UK Pay's experiences and approaches to this:

We started with a large manifest file to describe applications. This worked well for quick prototyping and getting our microservices running together on PaaS.

For compliance, we require infrastructure, particularly networking and security-related configuration to be carefully managed. Declarative configuration such as Terraform solves this, particularly as we started to build up a more complicated infrastructure and service topology.

We are currently using the CloudFoundry Terraform service provider. This works fine for declaring applications, networking rules, user-provided services, and some service bindings. We found it lacking in support for CF v3 API related functionality, particularly the creation and management of apps via the v3 API, which allows our CI tooling to deploy and restart applications using CF native zero-downtime features. 

We have [forked the provider](https://github.com/alphagov/terraform-provider-cf/pull/1) and added very limited support for v3 app management ourselves. I have also [engaged with the maintainer](https://github.com/cloudfoundry-community/terraform-provider-cf/issues/250) of the provider about appetite and approach to fully support v3 features.

**Comment by pauldougan** [comment]
Thanks for this suggestion @chrisfarms 

also worth pointing to [ADR002](https://pay-omnibus-docs.london.cloudapps.digital/adrs/0002-use-terraform-to-manage-the-environment-skeleton.html) in the Pay Architecture decision records

**Comment by saliceti** [comment]
I agree declarative is important. It removes the overhead of making a script idempotent for creating, updating and deleting resources as we don't have to care about the ordering or checking for existence. Especially when we rely on several different components depending on each other (service, app, route...).
The terraform plugin is actually good and covers most of the cf commands. It has some rough edges but is definitely a good foundation.

**Comment by pauldougan** [comment]
some context around the use of the CF terraform provider in the DCS https://github.com/alphagov/doc-checking/blob/govuk-paas/doc/paas-discovery/018-zero-downtime-deploys.md

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
