### ISSUE TITLE
[Feature Request] - expose S3 access logs

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#73]
**Is your feature request related to a problem? Please describe.**
We wanted to use PaaS supplied public S3 to serve files and instantly noticed that it doesn't provide any means to audit the use.

**Is this blocking you from doing anything?**
Reduces what we can use the public S3 for. E.g. it's ok not to have logs for application assets (CSS/JS) but not quite for published datasets as json files.
Also in case we were to serve files from private S3 using S3 signed URL we are missing auditability. 

**Describe the outcome you'd like**
Access logs that I can connect to a log drain.

**Describe the solutions you've considered**
Use native S3 on AWS, w/o PaaS wrap. With all the joys of selfmanagement.

**Additional context**
It's basically an audit need

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
