### ISSUE TITLE
Redis backing service metrics via Prometheus endpoints

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-roadmap#74]
## Objective

Enable our users to manage their Redis backing services more confidently, so they can:

- Avoid unnecessary reliability problems for users through capacity issues

- Reduce unnecessary costs through sizing their backing services more accurately

## How we'll solve the problem

We already provide these metrics via the GOV.UK PaaS admin interface. 

In addition, we will:

- Enable users to set up dashboards and alerts, via Prometheus endpoints

## Key Results:

- Our largest tenant is able to save money by scaling their Redis instances down to what is needed to satisfy their actual load

**Comment by pauldougan** [comment]
@46bit how about cross linking this roadmap item to the xgov slack [#govuk-paas](https://ukgovernmentdigital.slack.com/archives/C33SAH4GJ) and ask the community if anyone is interested in beta testing the new redis metrics.

**Comment by 46bit** [comment]
This is now deployed and usable. It's available to everyone but costs money we can't recharge yet. I suggest we wait for dynamic billing before widely advertising this, but it's available to anyone who asks.

**Comment by 46bit** [comment]
How to adopt this is now documented at https://docs.cloud.service.gov.uk/monitoring_services.html#exporting-backing-service-metrics-to-prometheus.
