### ISSUE TITLE
[Feature Request] - Key-prefix-based permissions for S3

### ISSUE THREAD

**Issue by michalc** [alphagov/paas-roadmap#76]
**Is your feature request related to a problem? Please describe.**
We would like multiple applications to write objects to, read objects from, and list objects in, the same S3 bucket, but each to only have permission to do so under a specific key-prefix.

This is for a "federated" public data repository where multiple applications have the ability to read/write data to their own area of a bucket [and another application would have read access to the entire bucket, which is already possible].

**Is this blocking you from doing anything?**
No, but only because we provision our own buckets in AWS directly and setup IAM policies as needed.

**Describe the outcome you'd like**
To have `-c` configuration option when binding an application to a bucket where you can specify a prefix, similar to how `read-only` permissions are configured at https://docs.cloud.service.gov.uk/deploying_services/s3/#bind-an-aws-s3-bucket-to-your-app.

**Describe the solutions you've considered**
We have considered allowing each application write access to the entire bucket, but would like to minimise impact if the application is buggy or is compromised.

**Additional context**
The initial/very early version of the public data repository is at https://github.com/uktrade/public-data-api

**Comment by tlwr** [comment]
(Perhaps obvious question but good to clarify)

Would you expect this to work in conjunction with `read-only` eg
```
cf bind-service ... \
  -c '{"permissions": "read-only", "paths": ["/prefix", "/other-prefix", "/nested/prefix"]}'
```

**Comment by michalc** [comment]
@tlwr I would expect it to work with `read-only`, yes, but...

...for our particular case, I realise we don't actually need that, since we need `read-write` under a prefix, and `read-only` for the whole bucket.

**Comment by tlwr** [comment]
Do you need the same service binding to have both global read and prefixed write?

**Comment by michalc** [comment]
@tlwr In our case, no, we won't need the same app to have both global read and prefixed write. 

Even if we did need, say application A to be able to read application B's data: it could fetch it via the public data repository which itself would have read access to everything.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.

**Comment by michalc** [comment]
@wryobservations I am aware of the news (and I admit slightly saddened by it too). Thanks for letting me know though
