### ISSUE TITLE
[Feature Request] - 'service' users

### ISSUE THREAD

**Issue by benvand** [alphagov/paas-roadmap#78]
**Is your feature request related to a problem? Please describe.**
I want to grant just 'space developer' in a given space to a user account and use it as a service deploy user that is never actually logged in to, but managed through the PAAS admin.
At the moment all users require an email address to activate the account, I was hoping to create these users without an email address.

**Describe the outcome you'd like**
I'd like to be able to create users that can deploy/ redeploy apps and administer them (inc passwords) through the PaaS admin.

**Describe the solutions you've considered**
The current work arounds involve the management of one or more email accounts/ groups in order to create paas accounts for service users.

**Additional context**
I had this need when I was looking up best practice and looking to deploy from Github actions. It's the principle of least permissions. 
I realised i would need a new paas user to do the deploy, then I realised that I'd need a new email address/ group, then I realised that I'd then need to make this group accessible to people in my google org. All of the new email stuff would be redundant if we could manage this entirely in the paas admin.

**Work arounds**
1. Single google group with '+' suffixes per service user:
  Google group:  programme-deploy@...
  PAAS Accounts:  programme-deploy+service-1@..., programme-deploy+service-2@...

2. Group per user which main group subscribes to
  Google groups:  programme-deploy@...(main group), programme-deploy-service-1@..., programme-deploy-service-2@...
  PAAS Accounts: programme-deploy-service-1@..., programme-deploy-service-2@...
  And subscribe main group to service deploy groups.

**Comment by markpeterbuckley** [comment]
Hi Ben, we're moving this back into the 'proposed' column for now as there have been other priorities on GOV.UK PaaS that have taken precedence. It is still something we are interested in and don't think it would be a humongous amount of work but wanted to let you know it won't be the 'next' thing we work on. Cheers.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
