### ISSUE TITLE
[Feature Request] - Allow webhooks to be set for events like push/restage 

### ISSUE THREAD

**Issue by matthewford** [alphagov/paas-roadmap#79]
Related to https://github.com/alphagov/paas-roadmap/issues/20 our CI pipeline currently notifies our slack channel when we initiate a deployment, however that doesn't tell us if the deployment succeeded, ideally, we would set up a webhook within CF that notifies us of the events that take place. 

**Is this blocking you from doing anything?**
Not really but our notifications currently are not that useful.

**Describe the outcome you'd like**
A webhook to listen to deployment events.

**Describe the solutions you've considered**
We push a notification to slack once the deployment starts but if it fails we can't capture that.

**Support links**
There is Pivotal Event Alerts which does something similar:
https://docs.pivotal.io/event-alerts/1-2/using.html

**Comment by 46bit** [comment]
Thanks for filing this, it’s an interesting feature request.

It’s doable to implement this for everything that triggers an Audit Event. (Everything that shows up in the “Events” tabs in our admin panel.)

That Pivotal link has a very interesting pattern, allowing alerting on things like high CPU. So this could line up with doing alerting.

**Comment by emilygds** [comment]
Hello again @matthewford. We discussed this today as a team. There is definitely something we could do to solve this particular problem (i.e. seeing whether deploys were successful or not, on Slack). This is also likely common to other users - although we'd welcome insights and votes from others. 

The solution might be a few stories to create an app that sent notifications, and would involve ongoing maintenance.

However, this is one of quite a few likely needs for notifications or alerts generally. Given the level of customisation, effort and maintenance to do it, we'd prefer to look at it in the context of alerting generally.

Given this, we've linked this request to [another, higher-level issue for additional monitoring and alerting](https://github.com/alphagov/paas-roadmap/issues/85).

We'd welcome any thoughts from you about any other priorities for notifications, alerts, if applicable. We're aware of a few already and will be adding them to the issue I mentioned above.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
