### ISSUE TITLE
[Feature Request] - resizable RDS instance types

### ISSUE THREAD

**Issue by philandstuff** [alphagov/paas-roadmap#84]
**Is your feature request related to a problem? Please describe.**
When users create an RDS instance, they have to choose a plan.  If their service has to scale, it's not easy to migrate from one plan to another.

**Is this blocking you from doing anything?**
No

**Describe the outcome you'd like**
Make RDS attributes such as instance type and disk size into configuration options rather than baked into the plan.  So that I can do:

    cf create-service postgres postgres12 mydb -c '{"instance_type":"db.m6g.large","disk_size":"300G"}'

Then, later, once my service has more traffic and needs to scale, I can do:

    cf update-service postgres postgres12 mydb -c '{"instance_type":"db.m6g.2xlarge","disk_size":"2T"}'

**Describe the solutions you've considered**
When trying to upsize an RDS instance, I could:

 - ask the PaaS team to manually do the upgrade and update the plan (don't even know if this is possible)
 - create a whole new service, migrate the data from the old service to the new service, schedule some maintenance time (during which the service is down or at least in read-only mode), do a final data migration, swap to the new service, decommission the old service.

**Additional context**
My feeling is that:

 - things that can be upgraded without forcing a complete new RDS instance should be configuration items
 - other things should be part of the plan

I'm not sure about how this interacts with maintenance windows.

Disk size is a tricky one: it's easier to make disks bigger than smaller.

This probably needs dynamic billing, because infrastructure cost would not be tied to plan.

Other things that this could enable:

 - users could explore different instance families (eg `db.r5`, `db.m6g`) to better tailor them to their workloads, but we should probably have a sensible default recommendation

**Support links**
None that I know of

**Tracker links**
None that I know of

**Comment by philandstuff** [comment]
Note: I think this is a neat idea but I don't have a direct need for it right now so prioritise accordingly.

If you are reading this and you have a need for this feature, please comment so that the paas team are aware of you.

**Comment by paroxp** [comment]
I would absolutely prefer this approach over the current system we have. Sadly, long time ago user research has indicated that the current system works better for people.

I would like to revisit that though, especially after we've grew selection quiet a bit...

**Comment by AP-Hunt** [comment]
I think the user need is probably real, but IMO this is exposing a bit much of the underlying provider to tenants; it requires them to know about the kinds of AWS RDS instance types. As a platform, we aim to make it easy for people to build and deploy their services without much need of infrastructure knowledge, and I think this as proposed would be step in the wrong direction.

I would suggest keeping the range of sizes we have now, and allowing tenants to change the size of the disk via the broker.

```
$ cf create-service postgres medium-ha-21 DB_NAME -c '{"disk_size": "200G"}'
$ cf update-service DB_NAME -c '{"disk_size": "250G"}'
```

> If their service has to scale, it's not easy to migrate from one plan to another.
We have tests for the broker that demonstrate the ability to change plans on an existing database, so it's definitely possible, at least in the simplest case. Can you describe the pain you've experienced whilst trying to do it for real?

**Comment by LeePorte** [comment]
Keeping the platform agnostic of provider was always an aim, so that if we needed to switch provider or go multi cloud it wouldn't have a tenant facing impact.

Pricing of services and billing for services is also part of this. Many tenants have to raise POs to cover the cost of their service for the year, and then draw down against them. Having predictability was certainly key for this due to complex processes. 

Some more user research into this is a good place to start

**Comment by paroxp** [comment]
> Keeping the platform agnostic of provider was always an aim, so that if we needed to switch provider or go multi cloud it wouldn't have a tenant facing impact.

This is only applicable if we were to stubbornly stay with a single provider instead of growing to many, like Aiven, Azure, DigitalOcean or ElephantSQL.

Perhaps an addition to this request would be to rename this offering to `rds-postgres`? This would allow us adding `rds-aurora-postgres`, `aiven-postgres` and few more later on, each with different set of options - reviewable at the documentation level.

**Comment by philandstuff** [comment]
> We have tests for the broker that demonstrate the ability to change plans on an existing database, so it's definitely possible, at least in the simplest case. Can you describe the pain you've experienced whilst trying to do it for real?

Huh I think my mental model was incorrect then, I didn't realise it was possible to change plan once a service was created.  If that's the case then I think this issue is somewhat misguided.

Going to leave it open as there's an interesting discussion but maybe this needs to be retitled "customizable RDS instance types"?  Also the user needs look very different now.

**Comment by markpeterbuckley** [comment]
Hello, Mr Potter. Given the customisable and configurable nature of the request it's something that we won't be able to enable unless we do work on our billing engine. We've had requests similar to this before, I am told, but given the vision of the platform to be 'simple for users' we have erred away from it to keep that focus. We can relook at it (pending user research) if we enable more nuanced billing. 

Going to close this and if we look at it again then "customizable RDS instance types" will probably be the title.
