### ISSUE TITLE
[Feature Request] - A supported way to monitor and alert for applications running on PaaS

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-roadmap#85]
**Is your feature request related to a problem? Please describe.**
When running an important web service you typically want to be aware of how it is performing. For instance you want to know about downtime, you want to know if it is erroring for users, and you want to know if it is behaving in unwanted/unexpected ways.

At present GOV.UK PaaS do not have a particularly supported way of doing that. We suggest users procure Logit to store logs, but we don't have a suggested alternative for metrics and alerting.

The feature request is have a supported way of monitoring metrics and issuing alerts. It should be easy to get started with, so that it fits with the PaaS not requiring major webops capability from our users.

**Is this blocking you from doing anything?**
We have talked to tenants about running Prometheus/Grafana/Alertmanager on PaaS, and several tenants are doing this. DfE directly run this on PaaS in production. GDS's own services such as Notify and Digital Marketplace use the same stack but run it in EC2.

However this is still a trial. We offer "best effort" sort of support, and don't offer much confidence that it will work.

**Describe the outcome you'd like**
A documented way to achieve the outcomes stated above. Monitoring and alerting for our users.

**Describe the solutions you've considered**
1. We can tell users to procure a third-party solution, such as Elastic's monitoring stack
2. We can give users a preconfigured Prometheus/Grafana/Alertmanager stack, set up with something repeatable like Terraform
3. We can give people a TICK stack instead, as briefly discussed in https://github.com/alphagov/automate-roadmap/issues/30

**Linked issues**

[In this issue](https://github.com/alphagov/paas-roadmap/issues/79), a user wanted to be able to see in Slack whether deploys happened successfully or not.

**Support links**
Links to support tickets related the feature request here.

**Tracker links**
Links to Pivotal Tracker stories related the feature request here.

**Comment by 46bit** [comment]
We're looking at doing user research on this. If you have a need for this, have views on how it should be done, or are interested then leave a reply and we can talk more about it.

**Comment by saliceti** [comment]
This is how we deploy the whole prometheus ecosystem to paas: https://github.com/DFE-Digital/bat-platform-building-blocks/blob/master/docs/terraform.md
And the separate modules: https://github.com/DFE-Digital/bat-platform-building-blocks/tree/master/terraform/modules
We could move this code to its own repo if there is an interest.

**Comment by markpeterbuckley** [comment]
Thanks for this, @saliceti. I think there would be definite interest so please do!

**Comment by saliceti** [comment]
@markpeterbuckley the terraform modules are now published for reuse: https://github.com/DFE-Digital/cf-monitoring/
Feedback is welcome!

**Comment by markpeterbuckley** [comment]
Excellent stuff! Thanks @saliceti 🙌

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
