### ISSUE TITLE
[Feature Request] - Smaller redis plan

### ISSUE THREAD

**Issue by saliceti** [alphagov/paas-roadmap#88]
**Is your feature request related to a problem? Please describe.**
We're trying to control costs of our teaching vacancies review apps.
A review app is a complete teaching vacancies paas environment created for each new pull request.
Each one consists of:
- 1 webapp
- 1 background process
- 1 redis
- 1 postgres

We are now looking back at the cost and how it could be optimised. In October we spent a total of £819.45 in the teaching-vacancies-review space. Breakdown:
- redis: 306.78
- postgres: 290.23
- apps: 222.43

Redis is the highest cost. Comparing paas and raw AWS:
- paas tiny-5.x: £21.89/month (+10%)
- AWS cache.t3.micro: $0.019/hour ~ $13.68/month ~ £10.29/month
Source: https://aws.amazon.com/elasticache/pricing/#On-Demand_Nodes

If the smallest plan were available in paas, we could make significant savings. Could it be made available?

**Is this blocking you from doing anything?**
Expanding review apps to all teams

**Describe the outcome you'd like**
A smaller redis plan is available in paas

**Describe the solutions you've considered**
Destroy and recreate redis instances as needed. It's doable but requires significant changes.

**Additional context**
https://govuk.zendesk.com/hc/requests/4352296

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
https://www.pivotaltracker.com/story/show/175872849

**Comment by AP-Hunt** [comment]
Hi Colin,

Putting this in the "Now" column whilst the change goes through review and makes its way out to live.

Regards,
Andy

**Comment by pauldougan** [comment]
great stuff, the PR is here https://github.com/alphagov/paas-cf/pull/2532

**Comment by LeePorte** [comment]
This PR has been deployed to prod, you now have a `micro-5.x` and a `micro-5.x-ha` plan available for use.
