### ISSUE TITLE
SFTP File Upload into S3 bucket not available on the Gov.UK PaaS

### ISSUE THREAD

**Issue by somnathc10** [alphagov/paas-roadmap#89]
**Is your feature request related to a problem? Please describe:**
At CCS, we've a business requirement to have 3rd party suppliers to upload files (.csv) using SFTP, in order for Spree apps to process these files. This is part of 'Buy a Thing' which is based around the Spree eCommerce platform that is dockerised Ruby on Rails apps. Gov.UK PaaS is currently doesn't support SFTP File Upload into S3 bucket

**Is this blocking you from doing anything?**
This is a business requirement to provide SFTP upload functionality for suppliers, as small to medium suppliers are dependent on the SFTP client as an easy process to upload product catalogues files

**Describe the outcome you'd like**
I'd appreciate if you could consider the SFTP upload in the roadmap

**Describe the solutions you've considered**
We're currently using AWS Transfer family to transfer files into and out of Amazon S3 storage over the SFTP.

**Any additional context:**
While Gov.UK PaaS doesn't support SFTP inbound currently, but can we import the uploaded files from AWS S3 bucket into Gov.UK PaaS Backing Service to s3?

## references
- ZENDESK-4278449

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
