### ISSUE TITLE
[Feature Request] - Ensure that all S3 buckets have access log enabled

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#90]
**Is your feature request related to a problem? Please describe.**
In case a service key leak or suspicious behaviour.

**Is this blocking you from doing anything?**
Incident investigation.

**Describe the outcome you'd like**
As a minimum, store these logs end allow for ticket based access during investigation.

Perfect solution would allow to aggregate the access logs in the user aggregated logging. See #73 

**Describe the solutions you've considered**
Direct usage of AWS supplied S3

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by markpeterbuckley** [comment]
It's on our radar as something to do. We will update you when we've had the time to work on this (we need to do this before we can do the work to expose them anyway!).

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
