### ISSUE TITLE
[Feature Request] - log all ssh terminal history and outputs

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#91]
**Is your feature request related to a problem? Please describe.**
Investigation of user behaviour

**Is this blocking you from doing anything?**
Investigation

**Describe the outcome you'd like**
All terminal history with command outputs being stored in a tenant aggregated logging.
Starting from providing the identity of a person opening the session.

**Describe the solutions you've considered**
Block SSH access

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by markpeterbuckley** [comment]
Hey, I think you might expect this but this isn't something we'd be comfortable enabling. As platform operators it would expose us to too much from a security point of view. One thing you could try is turning off SSH access by default, and if they do need it, they can turn it back on which would then generate an event visible in GOV.UK PaaS admin or you could alert on as out of the ordinary behaviour to investigate.
