### ISSUE TITLE
[Feature Request] - org and space level policy

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#92]
**Is your feature request related to a problem? Please describe.**
Risk management

**Is this blocking you from doing anything?**
Requires constant monitoring of users usage of the platform.

**Describe the outcome you'd like**
Ability to specify policy either on space or on org level that disables some functionality of PaaS.
Good Examples: NFS, Public S3, MySQL, Non HA instances of ES or PostgreSQL.

**Describe the solutions you've considered**
Self audit. Already in place.

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by markpeterbuckley** [comment]
Hey, this isn't something that is currently supported by Cloud Foundry (although there has been some [talk around it upstream](https://docs.google.com/document/d/1isfsSWvF8xDU0G69k4MqB3o5c2vB0P3Vbi79W0yvqFQ/edit)). It may or may not happen and might be easier with a CF on Kubernetes approach in the long term but we can't commit to it right now.
