### ISSUE TITLE
[Feature Request] - Expose service logs to the tenant

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#93]
**Is your feature request related to a problem? Please describe.**
E.g. in case of ES issues we have to bother you with tickets.

**Is this blocking you from doing anything?**
Troubleshooting.

**Describe the outcome you'd like**
Expose service logs (ES, PostgreSQL) into tenant aggregated logging.

**Describe the solutions you've considered**
Tickets to get logs. Migrated one ES node to AWS.

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by markpeterbuckley** [comment]
Hi @munhitsu, can I clarify that this means 'backing services' and not just the example of Elasticsearch? We'd like to do a spike into this to see what is possible to expose.

**Comment by munhitsu** [comment]
yes - this means all backing service. Postgres, Redis, Elasticsearch

Elasticsearch was a good example when the logs were needed

**Comment by mattonfoot** [comment]
CloudFront CDN logs - at least the HTTP request logs - would also be a good addition to enable log analysis.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
