### ISSUE TITLE
[Feature Request] - ARM/graviton based RDS/Redis for better value for money

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#94]
**Is your feature request related to a problem? Please describe.**
No. It's pure cost optimisation.

**Is this blocking you from doing anything?**
No

**Describe the outcome you'd like**
Ability to choose Graviton hosted RDS/Redis/ES plan. As it appears to be cheaper for the end user.

Maybe in the long term it would make sense to provide the compute node, but usually compute is a fraction of a cost comparing to the supporting services (Redis/ES).

**Describe the solutions you've considered**
None

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by markpeterbuckley** [comment]
Hi @munhitsu, thanks for this. As part of wider cost optimisation work for GOV.UK PaaS, we will consider this in the future balanced against performance, maintenance and other factors.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
