### ISSUE TITLE
[Feature Request] - NFS with strong permission model

### ISSUE THREAD

**Issue by munhitsu** [alphagov/paas-roadmap#95]
**Is your feature request related to a problem? Please describe.**
For data science loads we seek ability to have user running multiple containers to share the same home directory.

**Is this blocking you from doing anything?**
We use AWS for our Data Workspace.

**Describe the outcome you'd like**
Ability to host Data Workspace on PaaS.
Application user can spawn as many containers as he wants. These containers need to share his home directory.

**Describe the solutions you've considered**
AWS EFS
S3 sync

**Additional context**
N/A

**Support links (for GOV.UK PaaS folk only)**
N/A

**Tracker links (for GOV.UK PaaS folk only)**
N/A

**Comment by markpeterbuckley** [comment]
Hi @munhitsu, we're going to merge this with https://github.com/alphagov/paas-roadmap/issues/75 and make sure we reference this card. It's something we are very keen on exploring in the near future for use cases likes yours.
