### ISSUE TITLE
[Feature Request] - Billing metrics

### ISSUE THREAD

**Issue by saliceti** [alphagov/paas-roadmap#96]
**Is your feature request related to a problem? Please describe.**
Today it's difficult to automate the processing of billing information.

**Is this blocking you from doing anything?**
As an owner of spaces, I can't create a dashboard to see my day to day use and I can't create alerts when usage is above a budget or a forecast.

**Describe the outcome you'd like**
Billing metrics available in paas-prometheus-exporter so I can use them in grafana and alertmanager. This could be used to create a generic dashboard which any paas user could use.

**Describe the solutions you've considered**
- Manual check on the web portal
- Extract CSV from web portal and process via Excel
- Build a new service which would connect to the paas-billing API and make metrics available

**Additional context**

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by 46bit** [comment]
Hi Colin. While we don't have support for this yet, I believe you can access our billing API and pull your own data out. If memory serves DiT have done this to monitor their costs–maybe @munhitsu will know if they're still doing that and have any useful code to share.

**Comment by saliceti** [comment]
@46bit yes I could create my own exporter. But if the metrics were available in paas-prometheus-exporter this would be much easier.

**Comment by munhitsu** [comment]
In DIT we scrape the API and expose it for prometheus. Checkout the implementation:
https://github.com/uktrade/cost_monitor

**Comment by pauldougan** [comment]
hey @munhitsu you beat us to it, we were just discussing this issue earlier with the team and were going to post that link too!

**Comment by saliceti** [comment]
Thanks @munhitsu I'll give it a try!

**Comment by markpeterbuckley** [comment]
Hi @saliceti keep meaning to come back to this and thanks to @munhitsu for signposting what DIT have done in regards to this. There's also a ticket you raised last year around Billing API https://github.com/alphagov/paas-roadmap/issues/63 - I'm going to merge these two under a wider 'Improve billing support' or something similar as there are a number of problems we want to solve around billing that should be tackled all at once. It will undoubtedly require a bit of user research and we don't have a timeframe for this right now but we were hoping to get to 'future proofing billing' in the near future in general platform improvements. Basically, we hope to do something to address your needs, Colin, but it'll be a part of a wider piece so if Mat's work helps you out in the meantime then that will probably be the more time friendly solution.
