### ISSUE TITLE
Improve support for billing

### ISSUE THREAD

**Issue by markpeterbuckley** [alphagov/paas-roadmap#97]
**Is your feature request related to a problem? Please describe.**
* users need to be able to easily view and query their usage and billing on GOV.UK PaaS
* this is currently possible through the admin portal at an org and space level but only for individual months
* more flexible billing queries would be useful for tenants and operators, and potential finance and other stakeholders
* being able to see the usage in real time would enable tenants to monitor their costs and not get surprising bills
* the way bills are generated currently also means some additional features/services are possible to be added and charge for efficiently - sorting this would enable different types of service to be added

**Is this blocking you from doing anything?**
* we have evidence that the way the bills are generated is creating overhead for finance functions to cross charge and ledger effectively

**Describe the outcome you'd like**
* user research to find out how we can improve billing for tenants
* being able to generate bills with required parameters
* being able to export billing data into different monitoring tools
* being able to charge for 'usage' based services efficiently

**Additional context**
There have been a number of linked requests for billing improvements
e.g https://github.com/alphagov/paas-roadmap/issues/63
https://github.com/alphagov/paas-roadmap/issues/96

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
