### ISSUE TITLE
[Feature Request] - Support for Lambda@edge

### ISSUE THREAD

**Issue by Prash-M** [alphagov/paas-roadmap#98]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is and the impact to you. Ex. I can't deploy x due to y being unavailable 

Lambda@edge cryptographically validates the Cognito token passed by COLA (Cabinet Office Login Auth app). We would want this happen at edge location so that the user authentication is carried on away from the application itself. Depending on the outcome of the authentication user will be granted access to the underlying application.

**Is this blocking you from doing anything?**
A clear and concise description of any work that you are unable to complete.
Lack of lambda@edge means we are unable to migrate service from AWS to Gov.Uk PaaS

**Describe the outcome you'd like**
A clear and concise description of what you like to happen.
I would like PaaS to support Lambda@edge

**Describe the solutions you've considered**
A clear and concise description of any solutions or features you've considered.
We started with having a list of email addresses and an allow list of IP addresses for authentication. However with several departments using ZScaler and similar proxy solutions, this has just become too risky. We then looked at Okta and similar authentication solutions. We have decided against these solutions because of cost, timelines and also owing to an impending centralised auth solution. So, as a medium term tactical solution we have come up with COLA. And COLA needs lambda@edge to perform authentication.

**Additional context**

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by wryobservations** [comment]
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.
