### ISSUE TITLE
[Feature Request] - Support for S3 signed URLs

### ISSUE THREAD

**Issue by Prash-M** [alphagov/paas-roadmap#99]
**Is your feature request related to a problem? Please describe.**
We have a usecase where one of our services requires to send data extracts to users in a secure way. As notify doesn't support sending zip files (password protected) as attachments, we wanted to go down secure signed S3 URL option. The idea is to store the objects on S3 bucket and share a signed URL with users (time bound). Similar to something like explained here https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html

**Is this blocking you from doing anything?**
Lack of this feature is not necessarily blocking us, but forcing us to find a convoluted and not so elegant solution.

**Describe the outcome you'd like**
We would like Gov.Uk PaaS to support signed URLs for the objects stored in S3 buckets

**Describe the solutions you've considered**
We have considered encrypting the csv file and sending it as an attachment via notify -- but this is not supported by notify
We are now looking to implement custom auth mechanism to access S3 objects or even host the S3 on CO AWS account and then have signed URLs

**Additional context**

**Support links (for GOV.UK PaaS folk only)**
Links to support tickets related the feature request here.

**Tracker links (for GOV.UK PaaS folk only)**
Links to Pivotal Tracker stories related the feature request here.

**Comment by andrewcharnley** [comment]
We're using signed URL's with a PaaS S3 bucket already. I believe it may be incorrectly provisioned with public access however which isn't what I want. Disabling public access may remove the ACL which also permits signed URL's?

**Comment by markpeterbuckley** [comment]
@Prash-M you can find guidance on using signed URLs with GOV.UK PaaS in our documentation here https://docs.cloud.service.gov.uk/deploying_services/s3/#access-objects-in-a-private-aws-s3-bucket-using-presigned-urls as @andrewcharnley mentions it is possible. By providing the presigned URL it does provide people with that link access so that needs to be taken into consideration when sharing private buckets.
